import type { ReframePreset, ReframeSettings } from './types'

export const REFRAME_PRESETS: ReframePreset[] = [
  {
    id: 'tiktok-9-16',
    name: '抖音/TikTok',
    platform: 'tiktok',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    strategy: 'center-crop',
    backgroundType: 'blur',
    backgroundColor: '#000000',
    backgroundBlurRadius: 30,
    description: '9:16 竖屏，适用于抖音和TikTok',
  },
  {
    id: 'douyin-9-16',
    name: '抖音',
    platform: 'douyin',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    strategy: 'center-crop',
    backgroundType: 'blur',
    backgroundColor: '#000000',
    backgroundBlurRadius: 30,
    description: '9:16 竖屏，适用于抖音',
  },
  {
    id: 'instagram-1-1',
    name: 'Instagram 方形',
    platform: 'instagram',
    aspectRatio: '1:1',
    width: 1080,
    height: 1080,
    strategy: 'fit-with-background',
    backgroundType: 'blur',
    backgroundColor: '#000000',
    backgroundBlurRadius: 40,
    description: '1:1 方形，适用于Instagram Feed',
  },
  {
    id: 'instagram-story-9-16',
    name: 'Instagram 故事',
    platform: 'instagram-story',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    strategy: 'center-crop',
    backgroundType: 'blur',
    backgroundColor: '#000000',
    backgroundBlurRadius: 30,
    description: '9:16 竖屏，适用于Instagram 故事',
  },
  {
    id: 'instagram-reel-9-16',
    name: 'Instagram Reel',
    platform: 'instagram-reel',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    strategy: 'center-crop',
    backgroundType: 'blur',
    backgroundColor: '#000000',
    backgroundBlurRadius: 30,
    description: '9:16 竖屏，适用于Instagram Reel',
  },
  {
    id: 'xiaohongshu-1-1',
    name: '小红书',
    platform: 'xiaohongshu',
    aspectRatio: '1:1',
    width: 1242,
    height: 1242,
    strategy: 'fit-with-background',
    backgroundType: 'blur',
    backgroundColor: '#ffffff',
    backgroundBlurRadius: 40,
    description: '1:1 方形，适用于小红书',
  },
  {
    id: 'xiaohongshu-3-4',
    name: '小红书 3:4',
    platform: 'xiaohongshu',
    aspectRatio: '3:4',
    width: 1080,
    height: 1440,
    strategy: 'fit-with-background',
    backgroundType: 'blur',
    backgroundColor: '#ffffff',
    backgroundBlurRadius: 40,
    description: '3:4 竖屏，适用于小红书',
  },
  {
    id: 'facebook-4-5',
    name: 'Facebook',
    platform: 'facebook',
    aspectRatio: '4:5',
    width: 1080,
    height: 1350,
    strategy: 'fit-with-background',
    backgroundType: 'blur',
    backgroundColor: '#1877f2',
    backgroundBlurRadius: 40,
    description: '4:5 竖屏，适用于Facebook',
  },
  {
    id: 'youtube-shorts-9-16',
    name: 'YouTube Shorts',
    platform: 'youtube-shorts',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    strategy: 'center-crop',
    backgroundType: 'blur',
    backgroundColor: '#ff0000',
    backgroundBlurRadius: 30,
    description: '9:16 竖屏，适用于YouTube Shorts',
  },
  {
    id: 'youtube-16-9',
    name: 'YouTube',
    platform: 'youtube',
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    strategy: 'center-crop',
    backgroundType: 'solid-color',
    backgroundColor: '#000000',
    backgroundBlurRadius: 0,
    description: '16:9 横屏，适用于YouTube',
  },
  {
    id: 'kuaishou-9-16',
    name: '快手',
    platform: 'kuaishou',
    aspectRatio: '9:16',
    width: 1080,
    height: 1920,
    strategy: 'center-crop',
    backgroundType: 'blur',
    backgroundColor: '#ff4500',
    backgroundBlurRadius: 30,
    description: '9:16 竖屏，适用于快手',
  },
  {
    id: 'portrait-to-landscape-16-9',
    name: '竖转横 16:9',
    platform: 'custom',
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    strategy: 'fit-with-background',
    backgroundType: 'blur',
    backgroundColor: '#000000',
    backgroundBlurRadius: 50,
    description: '9:16 竖屏转为 16:9 横屏，带模糊背景',
  },
  {
    id: 'landscape-16-9',
    name: '横屏 16:9',
    platform: 'custom',
    aspectRatio: '16:9',
    width: 1920,
    height: 1080,
    strategy: 'center-crop',
    backgroundType: 'solid-color',
    backgroundColor: '#000000',
    backgroundBlurRadius: 0,
    description: '16:9 标准横屏',
  },
  {
    id: 'landscape-16-10',
    name: '横屏 16:10',
    platform: 'custom',
    aspectRatio: '16:10',
    width: 1920,
    height: 1200,
    strategy: 'center-crop',
    backgroundType: 'solid-color',
    backgroundColor: '#000000',
    backgroundBlurRadius: 0,
    description: '16:10 宽屏',
  },
  {
    id: 'landscape-4-3',
    name: '横屏 4:3',
    platform: 'custom',
    aspectRatio: '4:3',
    width: 1440,
    height: 1080,
    strategy: 'center-crop',
    backgroundType: 'solid-color',
    backgroundColor: '#000000',
    backgroundBlurRadius: 0,
    description: '4:3 传统横屏',
  },
]

export function getPresetById(id: string): ReframePreset | undefined {
  return REFRAME_PRESETS.find((p) => p.id === id)
}

export function getPresetsByPlatform(platform: string): ReframePreset[] {
  return REFRAME_PRESETS.filter((p) => p.platform === platform)
}

export function getPresetsByAspectRatio(aspectRatio: string): ReframePreset[] {
  return REFRAME_PRESETS.filter((p) => p.aspectRatio === aspectRatio)
}

export function createSettingsFromPreset(preset: ReframePreset): ReframeSettings {
  return {
    targetWidth: preset.width,
    targetHeight: preset.height,
    strategy: preset.strategy,
    backgroundType: preset.backgroundType,
    backgroundColor: preset.backgroundColor,
    backgroundBlurRadius: preset.backgroundBlurRadius,
    padding: {
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
  }
}

export const DEFAULT_REFRAME_SETTINGS: ReframeSettings = {
  targetWidth: 1080,
  targetHeight: 1920,
  strategy: 'center-crop',
  backgroundType: 'blur',
  backgroundColor: '#000000',
  backgroundBlurRadius: 30,
  padding: {
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
}
